var mongoose = require('mongoose');
var OrderSchema = new mongoose.Schema({
  id: Number,
  originatingAccountId: Number,
  fullfillmentAccountId: Number,
  toFirstName: String,
  toLastName: String,
  toAddress1: String,
  toAddress2: String,
  toCity: String,
  toState: String,
  toZipCode: Number,
  toHomePhone: String,
  toMobilePhone: String,
  toEmail: String,
  fromFirstName: String,
  fromLastName: String,
  fromAddress1: String,
  fromAddress2: String,
  fromCity: String,
  fromState: String,
  fromZipCode: Number,
  fromHomePhone: String,
  fromMobilePhone: String,
  fromEmail: String,
  orderStatus: Number,
  dateCreated: { type: Date, default: Date.now },
  dateModified: { type: Date, default: Date.now },
});
module.exports = mongoose.model('Order', OrderSchema);
